version: 1.0.{build}
branches:
  only:
  - feature/ci
  - develop

environment:
  ASIOSDK: C:\projects\ASIOSDK2.3
  JUCE_DIR: C:\projects\JUCE
  image: Visual Studio 2017
  platform: x64
  configuration: Release

before_build:
  ps: |
    cd C:\projects
    git clone --depth=1 --branch=master https://github.com/WeAreROLI/JUCE.git JUCE
    mkdir "JUCE Modules"
    cd "JUCE Modules"
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_organicui.git juce_organicui
    cd ..
    ls
after_build:
  cmd: 7z a %APPVEYOR_BUILD_FOLDER%\Chataigne-win-x64-bleedingedge.zip %APPVEYOR_BUILD_FOLDER%\Binaries\App\*.exe
  
artifacts:
  - path: Chataigne-win-x64-bleedingedge.zip

build:
  project: Builds/VisualStudio2017/Chataigne.sln
  verbosity: minimal
  parallel: true