sudo: required
dist: yakkety

language: cpp

git:
    depth: 1

notifications:
  email: false

before_install:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo add-apt-repository ppa:webkit-team/ppa
    - sudo apt-get update --fix-missing
    - sudo apt-get install -qq
        clang
        libfreetype6-dev
        libx11-dev
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libjack-dev
        libbluetooth-dev
        libgtk-3-dev
        libwebkit2gtk-4.0-dev
    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq
    - pwd
    - ls -d */
    - cd ..
    - pwd
    - git clone --depth=1 --branch=master https://github.com/julianstorer/juce.git JUCE
    - pwd
    - ls -d */

compiler:
    - clang

branches:
    only:
        - master

script:
    - export JUCE_MODULES_PATH=/home/travis/build/benkuper/JUCE/modules
    - make -C "Chataigne/Builds/LinuxMakefile/" 