sudo: required
dist: trusty
env:
  global:
  - FTP_USER=u67889354-benjamin
  - VERSION=1.0.2
after_success:
- cd /home/travis/build/benkuper/Chataigne/Builds/LinuxMakefile/build
- zip Chataigne
- curl --ftp-create-dirs -T Chataigne.zip -u $FTP_USER:$FTP_PASSWORD ftp://ftp.kuperberg.fr/chataigne/user/data/Chataigne-linux-x64-$VERSION-beta.zip
language: cpp
git:
  depth: 1
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_20a3ce80c34d_key -iv $encrypted_20a3ce80c34d_iv
  -in travis_enc.txt.enc -out travis_enc.txt -d
- export DEBIAN_FRONTEND=noninteractive
- sudo add-apt-repository ppa:webkit-team/ppa -y
- sudo apt-get update --fix-missing
- sudo apt-get update -qq
- sudo apt-get install -qq clang libfreetype6-dev libx11-dev libxinerama-dev libxrandr-dev
  libxcursor-dev libxcomposite-dev mesa-common-dev libasound2-dev freeglut3-dev libcurl4-gnutls-dev+
  libasound2-dev libjack-dev libbluetooth-dev libgtk-3-dev libwebkit2gtk-4.0-dev
- pwd
- ls -d */
- cd ..
- pwd
- git clone --depth=1 --branch=master https://github.com/WeAreROLI/JUCE.git JUCE
- mkdir "JUCE Modules"
- cd "JUCE Modules"
- git clone --depth=1 --branch=master https://github.com/benkuper/juce_organicui.git
  juce_organicui
- cd ..
- pwd
- ls -d */
compiler:
- clang
branches:
  only:
  - master
script:
- export JUCE_MODULES_PATH=/home/travis/build/benkuper/JUCE/modules
- make -C "Chataigne/Builds/LinuxMakefile/"
